# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160926_0829'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
    ]
