# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20160926_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
